sudo: required
language: node_js
node_js:
    - "node"
install:
    - "curl https://install.meteor.com | /bin/sh"
before_script:
    - meteor npm install --save react react-addons-pure-render-mixinreact-addons-pure-render-mixin@0.14.8 node_modules/react-addons-pure-render-mixin
    - npm install
script:
    - "npm run test"
